// header links
// export const HeaderLinks = [
//   {
//     'id': 1,
//     'title': 'Home',
//     'path': '/'
//   },
//   {
//     'id': 2,
//     'title': 'Experts',
//     'path': '/experts'
//   },
//   {

//     'id': 34,
//     'title': 'Options',
//     'path': '/options'
//   },
//   {
//     'id': 5,
//     'title': 'Live Streaming',
//     'path': '/live-streamings'
//   },
//   {
//     'id': 4,
//     'title': 'FAQ',
//     'path': '/faq'
//   },
//   {
//     'id': 5,
//     'title': 'Terms & Conditions',
//     'path': '/terms&conditions'
//   },
//   {
//      'id': 43434,
//      'title': 'Blogs',
//     'path': '/blogs'
//   },

// ]

// Main Home Page Categories data
export const categoriesData = {
  categories: [
    {
      name: "Business & Entrepreneurship",
      image:
        "https://taskup.wp-guppy.com/storage/project-categories/post-1-15.jpg",
      subcategories: [
        {
          name: "Startup",
          count: 2,
          link: "#",
        },
        {
          name: "Business Strategies",
          count: 3,
          link: "#",
        },
        {
          name: "Human Resources",
          count: 0,
          link: "#",
        },
      ],
    },
    {
      name: "Health and Wellness",
      // "image": dental,
      image:
        "https://images.pexels.com/photos/356040/pexels-photo-356040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      subcategories: [
        {
          name: "Surgery",
          count: 0,
          link: "#",
        },
        {
          name: "OBG/GYN",
          count: 0,
          link: "#",
        },
        {
          name: "Pain",
          count: 0,
          link: "#t",
        },
      ],
    },
    {
      name: "Computers & Systems",
      // "image": Entertainment,
      image:
        "https://images.pexels.com/photos/442152/pexels-photo-442152.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      subcategories: [
        {
          name: "Programming",
          count: 2,
          link: "#",
        },
        {
          name: "Phone Applications",
          count: 3,
          link: "#",
        },
        {
          name: "Social Media",
          count: 0,
          link: "#",
        },
      ],
    },
    {
      name: "Sports & Sports Training",
      image:
        "https://images.pexels.com/photos/1192027/pexels-photo-1192027.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      subcategories: [
        {
          name: "Track & Field",
          count: 0,
          link: "#",
        },
        {
          name: "Football",
          count: 0,
          link: "#",
        },
        {
          name: "Sports Management",
          count: 0,
          link: "#",
        },
      ],
    },
    {
      name: "Beauty",
      image:
        "https://images.pexels.com/photos/1499517/pexels-photo-1499517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      subcategories: [
        {
          name: "Cosmetic Surgery",
          count: 2,
          link: "#",
        },
        {
          name: "Body Contour",
          count: 0,
          link: "#g",
        },
        {
          name: "Skin Care",
          count: 0,
          link: "#",
        },
      ],
    },
    {
      name: "Fashion",
      image:
        "https://images.pexels.com/photos/3755706/pexels-photo-3755706.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      subcategories: [
        {
          name: "Fashion Designing",
          count: 2,
          link: "#",
        },
        {
          name: "Costumes",
          count: 0,
          link: "#g",
        },
        {
          name: "Costume designing",
          count: 0,
          link: "#",
        },
      ],
    },
    {
      name: "Cyber Security",
      image:
        "https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      subcategories: [
        {
          name: "Risk Analysis",
          count: 1,
          link: "#",
        },
        {
          name: "Ethical Hacking",
          count: 0,
          link: "#",
        },
        {
          name: "Cloud Computing",
          count: 0,
          link: "#",
        },
      ],
    },
    {
      name: "Government",
      // "image": finance,
      image:
        "https://images.pexels.com/photos/2100942/pexels-photo-2100942.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      subcategories: [
        {
          name: "Contracting",
          count: 0,
          link: "#",
        },
        {
          name: "Housing",
          count: 0,
          link: "#",
        },
        {
          name: "Social Security",
          count: 0,
          link: "#",
        },
      ],
    },
  ],
};

// Main Home Page Project data
export const projectData = [
  {
    name: "Swinney Swinney",
    image: "https://taskup.wp-guppy.com/storage/profiles/avatar-1-15.jpg",
    verified: true,
    title: "Your path to holistic well-being.",
    postedAgo: "Joined date 9/14/2023",
    location: "England, United Kingdom",
    language: "English",
    level: "Senior level",
    calls: 6,
    priceType: "Fixed price",
    priceRange: "$00/hr",
    link: "/view-profile",
    reviews: 24,
  },
  {
    name: "Antony Clara",
    image: "https://taskup.wp-guppy.com/storage/profiles/avatar-3-6.jpg",
    verified: true,
    title: `Exploring the tech world's latest wonders`,
    postedAgo: "Joined date 9/14/2023",
    location: "UK",
    language: "Vietnami",
    level: "Junior level",
    calls: 3,
    priceType: "Fixed price",
    priceRange: "$00/hr",
    link: "/view-profile",
    reviews: 64,
  },
  {
    name: "John Doe",
    image: "https://taskup.wp-guppy.com/storage/profiles/avatar-3.jpg",
    verified: false,
    title: "Wanderlust made easy with Expert tips.",
    postedAgo: "Joined date 6/14/2023",
    location: "New York, USA",
    language: "Franch",
    level: "Expert level",
    calls: 56,
    priceType: "Hourly price",
    priceRange: "$00/hr",
    link: "/view-profile",
    reviews: 14,
  },
  {
    name: "Emma Smith",
    image: "https://taskup.wp-guppy.com/storage/profiles/avatar-6.jpg",
    verified: true,
    title: "Your guide to lifelong learning.",
    postedAgo: "Joined date 6/11/2023",
    location: "San Francisco, USA",
    language: "Italian",
    level: "Senior level",
    calls: 23,
    priceType: "Fixed price",
    priceRange: "$00/hr",
    link: "/view-profile",
    reviews: 24,
  },
  {
    name: "Sarah Johnson",
    image: "https://taskup.wp-guppy.com/storage/profiles/avatar-4.jpg",
    verified: false,
    title: "Satisfying your culinary cravings.",
    postedAgo: "Joined date 3/14/2023",
    location: "Span",
    language: "Spanish",
    level: "Mid level",
    calls: 21,
    priceType: "Hourly price",
    priceRange: "$00/hr",
    link: "/view-profile",
    reviews: 56,
  },
  {
    name: "Michael Anderson",
    image: "https://taskup.wp-guppy.com/storage/profiles/avatar-5.jpg",
    verified: true,
    title: "Elevate your everyday living.",
    postedAgo: "Joined date 4/14/2023",
    location: "Los Angeles, USA",
    language: "English",
    level: "Expert level",
    calls: 12,
    priceType: "Fixed price",
    priceRange: "$00/hr",
    link: "/view-profile",
    reviews: 4,
  },
];

//languages
export const languages = [
  {
    name: "English",
  },
  {
    name: "Spanish",
  },
  {
    name: "French",
  },
  {
    name: "German",
  },
  {
    name: "Portuguese (Brazil)",
  },
  {
    name: "Portuguese (Portugal)",
  },
  {
    name: "Russian",
  },
  {
    name: "Chinese",
  },
  {
    name: "Vietnamese",
  },
];

// countries data
export const countriesData = [
  { name: "Afghanistan", code: "AF" },
  { name: "land Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: 'Cote D"Ivoire', code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: 'Korea, Democratic People"S Republic of', code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: 'Lao People"S Democratic Republic', code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

// options data
export const options = [
  { value: "php", label: "php" },
  { value: "laravel", label: "laravel" },
  { value: "html", label: "html" },
  { value: "css", label: "css" },
];

// languages data
export const languagesData = [
  { value: "english", label: "english" },
  { value: "spanish", label: "spanish" },
  { value: "french", label: "french" },
  { value: "german", label: "german" },
  { value: "portuguese", label: "portuguese" },
];

// expert header
export const expertHeaderLinks = [
  {
    id: 1,
    title: "Dashboard",
    path: "/dashboard",
    icoClass: "bi bi-bar-chart",
  },
  {
    id: 2,
    title: "My Appointments",
    path: "/appointments",
    icoClass: "bi bi-file-text",
  },
  {
    id: 3,
    title: "Transactions",
    path: "/transactions",
    icoClass: "bi bi-exclamation-triangle",
  },
  {
    id: 4,
    title: "Withdrawals",
    path: "/withdraws",
    icoClass: "bi bi-bag",
  },
  {
    id: 5,
    title: "Call logs",
    path: "/calllogs",
    icoClass: "bi bi-telephone",
  },
  {
    id: 6,
    title: "Find experts",
    path: "/experts",
    icoClass: "bi bi-search",
  },
  // {
  //   'id': 7,
  //   'title': 'Subscriptions',
  //   'path': '/subscription',
  //   'icoClass': 'bi bi-life-preserver'
  // },
  // {
  //   'id': 8,
  //   'title': 'Support',
  //   'path': '/support',
  //   'icoClass': 'bi bi-life-preserver'
  // },
  {
    id: 9,
    title: "Schedule",
    path: "/schedule",
    icoClass: "bi bi-calendar",
  },
  // {
  //   id: 10,
  //   title: "Referral Team",
  //   path: "/refferal-team",
  //   icoClass: "bi bi-people",
  // },
  // {
  //   'id': 9,
  //   'title': 'My Requests',
  //   'path': '/requests',
  //   'icoClass': 'bi bi-circle'
  // },
];

// expert sidebar
export const sidebarLinks = [
  {
    id: 1,
    title: "Profile settings",
    path: "/settings",
    icoClass: "bi bi-person",
  },
  {
    id: 2,
    title: "Skill information verification",
    path: "/identity-verification",
    icoClass: "bi bi-check-square",
  },
  {
    id: 3,
    title: "Billing information",
    path: "/billing-information",
    icoClass: "bi bi-credit-card",
  },
  {
    id: 4,
    title: "Account settings",
    path: "/account-settings",
    icoClass: "bi bi-gear",
  },
  {
    id: 5,
    title: "Portfolio settings",
    path: "/portfolio-settings",
    icoClass: "bi bi-sliders",
  },
  {
    id: 6,
    title: "Social media",
    path: "/socialMedia",
    icoClass: "bi bi-hdd-network",
  },
  {
    id: 7,
    title: "Qualification settings",
    path: "/qualification-settings",
    icoClass: "bi bi-mortarboard",
  },
  {
    id: 8,
    title: "Wallet Settings",
    path: "/add-wallet",
    icoClass: "bi bi-wallet",
  },
  {
    id: 9,
    title: "Referral Code",
    path: "/update-refferal",
    icoClass: "bi bi-people",
  },
  {
    id: 10,
    title: "Bio Link",
    path: "/media-posts",
    icoClass: "bi bi-pencil",
  },
  {
    id: 11,
    title: "Bio Profile",
    path: "/bio-profile",
    icoClass: "bi bi-people",
  },
];

export const plans = [
  {
    title: "Pro Level 1",
    subtitle: "Small Office/Home Office",
    price: "16",
    features: [
      "Unlimited Calling Minutes",
      "Pro Level 1 Badge",
      "Be in Top Searches",
      "Upgrade to Pro Level 1",
    ],
    isBtn: true,
  },
  {
    title: "Master",
    subtitle: "Small Office/Home Office",
    price: "50",
    features: [
      "Enable Live Streaming",
      "Unlimited Calling Minutes",
      "Pro Level 3 Badge",
      "Be in Top Searches",
      "Upgrade to Master Level",
    ],
    isPopular: true,
  },
  {
    title: "Pro Level 2",
    subtitle: "Small Office/Home Office",
    price: "33",
    features: [
      "Enable Live Streaming",
      "Unlimited Calling Minutes",
      "Pro Level 2 Badge",
      "Be in Top Searches",
      "Upgrade to Pro Level 2",
    ],
  },
];
